name: Sync Repository Action
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: x-ddr/sync-repo-to-gitee@v1.0
      env:
          # 在 Settings->Secrets 配置 GITEE_KEY
          SSH_KEY: ${{ secrets.GITEE_KEY }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          github-repo: "https://github.com/DevelopJP/syzoj.git"
          # 注意替换为你的 Gitee 目标仓库地址
          gitee-repo: "git@gitee.com:jpdevelop/syzoj.git"
